---
layout: post
title: Flashcom Video Player Source
date: 2005-01-17 07:34:18.000000000 +05:30
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Technology
tags:
- Adobe
- Bandwidth
- Branden Hall
- Buttons
- downloads
- flash
- flash media server
- Flashcom
- Flem
- flv
- Macromedia
- Media
- Model-View-Presenter
- MovieClips
- MTASC
- MVP
- Object Oriented Programming
- OOP
- Source Code
meta:
  dsq_thread_id: '146363827'
  bitly_short_url: http://j.mp/jc0rjY
  retweet_cache: '1309569990:0'
  trx_addons_post_views_count: '41'
author:
  login: Brajeshwar
  email: brajeshwar@gmail.com
  display_name: Brajeshwar
  first_name: Brajeshwar
  last_name: Oinam
permalink: "/2005/flashcom-video-player-source/"
excerpt: A Flashcom Application coded with OOP patterned to MVP, to detect user bandwidth
  and play specific FLV. The application uses Object Oriented Progamming Methodology
  and is patterned closely to Model-View-Presenter.
---
<p>The title would have been much better if I can have a full sentence; "A Flashcom Application coded with OOP patterned to MVP, to detect user bandwidth and play specific FLV".</p>
<p>We have recently been fascinated by a fad; "no hanging codes on frames". You can remember the old days of Flash 5 when there was no option but to write piggy-bag codes on Buttons and MovieClips. But hey, there was "Flem (Flem)":http://chattyfig.figleaf.com/flem/ (by "Branden Hall (Branden Hall)":http://www.waxpraxis.org/), which helped you write codes pretty much on the frames and not really on top of the MovieClips. But then as Flash/ActionScript evolved into a more matured form, things have taken shape in a much better way.</p>
<p><!--more--></p>
<p>The next step was collection of Scripts/Codes on a single frame on the main timeline if possible and a few ones on the frame(s) of nested MovieClips. But then with more advancement and the ability to code more and more in an OOP manner, we can now reduce the number of frames where codes are hung in your FLA. If you look at the current application, you can see a single include file that initialize the necessary modules and the presenter took over the whole thing. Well, you virtually write everything in your favorite Text-Editor without taxing on Flash to do the loooooooooong compilation everytime you publish your Flash Document (Movie). Oh! Yes, "MTASC (MTSC)":http://www.mtasc.org/ have been a boon for ActionScript 2 Compilation.</p>
<p><strong>About the Application</strong></p>
<p>This application check the bandwidth speed of a user accessing the application and serves a particular flash video (flv) accordingly. The settings/configuration is configured in an external "config.xml".</p>
<p>The importance here is not really what the application can do but on how to approach, adapt a methodology on building a Rich Internet Application with AS 2.0, adapting OOP/DP.</p>
<p>The application uses Object Oriented Programming Methodology and is patterned closely to Model-View-Presenter. Macromedia Flash MX 2004 Professional was used for the application and coded in ActionScript 2.0.</p>
<p>This application is distributed under the GNU GENERAL PUBLIC LICENSE<br />
A copy of the license text is available at "http://www.gnu.org/copyleft/gpl.html (GNU GENERAL PUBLIC LICENSE)":http://www.gnu.org/copyleft/gpl.html</p>
<p>System Requirements, Installation/Deployment instructions are included in the Readme.txt file included with the either of the source downloads. You can read through the Class Documentation generated by the Community edition of BLDoc.</p>
<p>* <a href="http://downloads.brajeshwar.com/flashcom/videoplayer/" title="Preview Application">Preview Application</a> (currently not available)<br />
* <a href="http://downloads.brajeshwar.com/flashcom/videoplayer/doc/" title="Class Documentation">Class Documentation</a></p>
<p><strong>Source File Downloads</strong></p>
<p>* <a href="http://downloads.brajeshwar.com/flashcom/videoplayer/fcsvideoplayervideo.zip" title="">With Video (7mb)</a><br />
* <a href="http://downloads.brajeshwar.com/flashcom/videoplayer/fcsvideoplayer.zip" title="">Without Video (34kb)</a></p>
