---
layout: post
title: Adobe Flash can modify Router's UPnP Interface
date: 2008-01-27 07:28:51.000000000 +05:30
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Technology
tags:
- Adobe
- Configuration
- flash
- Preferences
- Router
- Security
- Settings
meta:
  dsq_thread_id: '135616805'
  bitly_short_url: http://j.mp/lss3nw
  retweet_cache: '1309541661:0'
  trx_addons_post_views_count: '45'
author:
  login: Brajeshwar
  email: brajeshwar@gmail.com
  display_name: Brajeshwar
  first_name: Brajeshwar
  last_name: Oinam
permalink: "/2008/adobe-flash-can-modify-routers-upnp-interface/"
excerpt: The generation of SOAP messages using the Flash plug-in enables the attacker
  to avoid the problem of password authentication, and the fact that many home routers
  are configured to accept SOAP messages without any type of authentication compounds
  the threat.
---
<p>Isn't it a perfect Sunday to read another lambast of the Flash Player for Security Issues?</p>
<p>Security firms and Interested Institutes keeps stumbling on security issues and vulnerabilities almost every waking hour of the day. Very recently, Google Researchers documented serious <a href="http://www.brajeshwar.com/2007/google-researchers-found-vulnerabilities-in-flash/">vulnerabilities in Adobe Flash SWFs</a>. Another Flash related security issues surfaced about a weeks ago that the Universal Plug and Play (UPnP) interface of <a href="http://www.gnucitizen.org/blog/hacking-the-interwebs">your Router may be highly vulnerable</a> to use by hackers seeking to modify their settings -- such as choice of DNS Server -- from an external location using Flash.<br />
<!--more--><br />
<strong>How?</strong></p>
<p>With Adobe Flash, attackers may corrupt the UPnP interface in the router and modify router settings by leveraging simple object access protocol messages (SOAP) to circumvent password protection or even the WPA (Wi-Fi Protected Access) encryption standard on routers.</p>
<p>Attacks generated by exploiting the UpnP interface may be <a href="http://www.gnucitizen.org/blog/hacking-the-interwebs">a hundred times more dangerous</a> than a recent attack in the wild using Flash and built on JavaScript host-scanning techniques. Nonetheless, researchers said they do not expect to see widespread exploit. It may be noted that in many cases, UPnP is remotely exploitable without interaction required from the victim, and all the attackers need to know is the IP address of the exploitable device.</p>
<p>The generation of SOAP messages using the Flash plug-in enables the attacker to avoid the problem of password authentication, and the fact that many home routers are configured to accept SOAP messages without any type of authentication compounds the threat, <a href="http://www.scmagazineus.com/Adobe-Flash-plug-and-play-interface-can-be-used-to-modify-router-settings/article/104421/">researchers said</a>.</p>
<p><strong>Adobe's suggestion to the issue</strong></p>
<p>The suggested work-around from Adobe is that malicious router commands delivered via SOAP requests can be circumvented by disabling this functionality in the router. Turning off your UPnP will make life harder and probably your Skype or MSN wont work as flawlessly as before.</p>
<p>You can <a href="http://www.gnucitizen.org/blog/hacking-the-interwebs">download</a> a Harmless/Useless Proof of Concept code from GNU Citizen, for demonstration and eduction purposes.</p>
